### ISSUE TITLE
Remove characters from pool option and/or option to generate more than one team.

### ISSUE THREAD

**Issue by Elive1** [Pustur/genshin-impact-team-randomizer#5]
Hey, thanks for the awesome work - this is looking to be a very practical tool! There is one feature that I would like to see that hasn't been listed in the current issues yet.
I like doing abyss randomizers and I like to reroll new teams for every floor without reusing characters. This can be achieved by either adding the option of having characters be removed from the pool after they have been rolled once or by rolling mutliple teams at once (here it can be an option if characters can appear in multiple teams or not).
Keep up the good work!

**Comment by Pustur** [comment]
Hi @Elive1,

Thanks for the feedback, having a customizable amount of teams to generate sounds like something I could implement. I'll consider it.  
Unfortunately I don't think I'm going to have time for this project anytime soon.

**Comment by adnan007d** [comment]
Hey, can I work on it?

**Comment by Pustur** [comment]
Feature to generate multiple teams at once released in `1.4.0`
