### ISSUE TITLE
External link to the randomizer with preset teams is not working

### ISSUE THREAD

**Issue by iamgei** [Pustur/genshin-impact-team-randomizer#6]
the randomizer with present teams isn´t avaible

**Comment by Pustur** [comment]
Hi @iamgei, thanks for noticing that. 

I don't own or operate that website. Last time I checked it was also not updated in 7 months. 

I'll notify the owner and if the website doesn't go back online I'll remove the link in the next version

**Comment by Pustur** [comment]
I just received the following response from the owner:

> hey, yeah the domain expired and I do not have the means to maintain it, appreciate you letting me know

> feel free to remove the link, ive had to prioritize other things
